language: php
sudo: false
git:
    depth: 1

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.app/cache

env:
  global:
    - deps="no"
    - SYMFONY_VERSION=""
    - CHECK_PHP_SYNTAX="no"
    # needed to avoid some Doctrine related deprecations
    - SYMFONY_DEPRECATIONS_HELPER="100"

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise

before_install:
  - stty cols 120
  - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [[ "$TRAVIS_EVENT_TYPE" != "cron" ]]; then rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini; fi;

script:
  - free -m
